<?php
/**
 * @file
 * rory_theme_settings_.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function rory_theme_settings__default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['menu-menu-footer-menu'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'menu-footer-menu',
    'module' => 'menu',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => 'footer',
        'status' => 1,
        'theme' => 'bartik',
        'weight' => -8,
      ),
      'rorydunn' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'rorydunn',
        'weight' => -7,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
