<?php
/**
 * Implements hook_block_info().
 */
function my_blog_block_info() {

  $blocks = array();
  $blocks['custom_footer_block'] = array(
    //Sets Block Name
    'info' => t('Custom Footer Block'),
    'visibility' => BLOCK_VISIBILITY_LISTED,
    //Pages where block is displayed set here
    'pages' => "*",
  );

    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function my_blog_block_view($delta = '') {
  // The $delta parameter tells us which block is being requested.
  if ($delta == 'custom_footer_block') {

    //Gets the links information for the specified menu
    $links = menu_build_tree('menu-footer-menu');

    //Provides template with required data to theme the menu
    $block['content'] = theme("custom_footer_block", array(
        'links' => $links,
      )
    );
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function my_blog_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['custom_footer_block'] = array(
    'render element' => 'content',
    'template' => 'custom-footer-block',
    'variables' => array('links' => NULL),
    'path' => drupal_get_path('module', 'my_blog') . '/templates',
  );
  return $theme;
}
